//! Generate `crates/l123-graph/src/icon_data.rs` from a local
//! `ICONS3.DAT` file.
//!
//! Usage:
//!   cargo run -p l123-graph --example gen_icon_data -- \
//!     <path-to-ICONS3.DAT> <output-rs>
//!
//! Run once to (re)produce the committed `icon_data.rs`. The output
//! contains 105 × 72-byte monochrome bitmaps (Section 3), 105 × 576-
//! byte palette-index bitmaps decoded from Section 4, and the hover-
//! help descriptions — used by `icons.rs` at render time so the
//! v3.4 panels look pixel-identical to the original.

use std::env;
use std::fs;
use std::io::Write;

use l123_graph::decode_color_bitmap;

const ICON_COUNT: usize = 105;
const BITMAP_BYTES: usize = 72;
const COLOR_BITMAP_PIXELS: usize = 24 * 24;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: {} ICONS3.DAT output-rs", args[0]);
        std::process::exit(1);
    }
    let data = fs::read(&args[1]).expect("read ICONS3.DAT");
    let out_path = &args[2];

    let ptr_strings_end = u16::from_le_bytes([data[0x04], data[0x05]]) as usize;
    let ptr_mono = u16::from_le_bytes([data[0x08], data[0x09]]) as usize;
    let ptr_rle = u16::from_le_bytes([data[0x0a], data[0x0b]]) as usize;
    let ptr_eof = u16::from_le_bytes([data[0x0c], data[0x0d]]) as usize;

    // Monochrome bitmaps (Section 3).
    let mut bitmaps: Vec<[u8; BITMAP_BYTES]> = Vec::with_capacity(ICON_COUNT);
    for i in 0..ICON_COUNT {
        let rel = u16::from_le_bytes([data[ptr_mono + i * 2], data[ptr_mono + i * 2 + 1]]) as usize;
        let off = ptr_mono + rel;
        let mut buf = [0u8; BITMAP_BYTES];
        buf.copy_from_slice(&data[off..off + BITMAP_BYTES]);
        bitmaps.push(buf);
    }

    // Section-4 RLE colour bitmaps. The offset table lives at the
    // section start; each entry is a u16 offset relative to `ptr_rle`.
    // Record `i` runs from offsets[i] to offsets[i+1] (or `ptr_eof` for
    // the last).
    let mut rle_offsets: Vec<usize> = (0..ICON_COUNT)
        .map(|i| u16::from_le_bytes([data[ptr_rle + i * 2], data[ptr_rle + i * 2 + 1]]) as usize)
        .collect();
    rle_offsets.push(ptr_eof - ptr_rle);

    let mut color_bitmaps: Vec<[u8; COLOR_BITMAP_PIXELS]> = Vec::with_capacity(ICON_COUNT);
    let mut color_available: Vec<bool> = Vec::with_capacity(ICON_COUNT);
    let mut rle_failed: Vec<(usize, String)> = Vec::new();
    for i in 0..ICON_COUNT {
        let start = ptr_rle + rle_offsets[i];
        let end = ptr_rle + rle_offsets[i + 1];
        let rec = &data[start..end];
        match decode_color_bitmap(rec) {
            Ok(bm) => {
                color_bitmaps.push(bm.pixels);
                color_available.push(true);
            }
            Err(e) => {
                // Leave colour bitmap empty so the renderer falls back
                // to the mono + category-tint path for this icon.
                color_bitmaps.push([0u8; COLOR_BITMAP_PIXELS]);
                color_available.push(false);
                rle_failed.push((i, format!("{e}")));
            }
        }
    }
    if !rle_failed.is_empty() {
        eprintln!(
            "warning: {} RLE records failed to decode:",
            rle_failed.len()
        );
        for (i, msg) in &rle_failed {
            eprintln!("  icon {i}: {msg}");
        }
    }

    // Descriptions: null-terminated strings starting at 0xB6 (just
    // past the offset table). We collect up to ICON_COUNT of them and
    // pad with empty strings if the catalog is shorter.
    let mut descriptions: Vec<String> = Vec::new();
    let mut i = 0xB6;
    while i < ptr_strings_end && descriptions.len() < ICON_COUNT {
        let s = i;
        while i < ptr_strings_end && data[i] != 0 {
            i += 1;
        }
        let raw = std::str::from_utf8(&data[s..i]).unwrap_or("");
        // Filter out trailing garbage (binary leakage past the
        // semantically-described entries).
        let clean = if raw
            .chars()
            .all(|c| c.is_ascii() && (c == ' ' || !c.is_control()))
        {
            raw.to_string()
        } else {
            String::new()
        };
        descriptions.push(clean);
        i += 1;
    }
    while descriptions.len() < ICON_COUNT {
        descriptions.push(String::new());
    }

    let mut f = fs::File::create(out_path).expect("create output");
    writeln!(
        f,
        "//! Auto-generated by `cargo run -p l123-graph --example gen_icon_data`."
    )
    .unwrap();
    writeln!(
        f,
        "//! Source: ICONS3.DAT from Lotus 1-2-3 R3.4 (used under license)."
    )
    .unwrap();
    writeln!(f, "//! Edit by re-running the generator, not by hand.").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// Number of icons in the catalog.").unwrap();
    writeln!(f, "pub const ICON_COUNT: usize = {ICON_COUNT};").unwrap();
    writeln!(
        f,
        "/// Bytes per icon bitmap (24×24 monochrome, MSB-first, 0=ink)."
    )
    .unwrap();
    writeln!(f, "pub const BITMAP_BYTES: usize = {BITMAP_BYTES};").unwrap();
    writeln!(f, "/// Bitmap pixel dimensions.").unwrap();
    writeln!(f, "pub const BITMAP_DIM: u32 = 24;").unwrap();
    writeln!(f).unwrap();
    writeln!(
        f,
        "/// 105 monochrome 24×24 icon bitmaps from Section 3 of ICONS3.DAT, indexed by icon ID."
    )
    .unwrap();
    writeln!(
        f,
        "pub const ICON_BITMAPS: [[u8; BITMAP_BYTES]; ICON_COUNT] = ["
    )
    .unwrap();
    for (i, bm) in bitmaps.iter().enumerate() {
        write!(f, "    [").unwrap();
        for (j, b) in bm.iter().enumerate() {
            if j > 0 && j % 12 == 0 {
                write!(f, "\n     ").unwrap();
            }
            write!(f, "0x{b:02x},").unwrap();
            if j % 12 != 11 && j != bm.len() - 1 {
                write!(f, " ").unwrap();
            }
        }
        writeln!(f, "], // {i}").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(
        f,
        "/// Pixels per colour bitmap (24 × 24, one byte per palette index 0..=7)."
    )
    .unwrap();
    writeln!(
        f,
        "pub const COLOR_BITMAP_PIXELS: usize = {COLOR_BITMAP_PIXELS};"
    )
    .unwrap();
    writeln!(f).unwrap();
    writeln!(
        f,
        "/// 105 palette-indexed 24×24 bitmaps decoded from Section 4 of ICONS3.DAT."
    )
    .unwrap();
    writeln!(f, "///").unwrap();
    writeln!(
        f,
        "/// Each byte is a palette index 0..=7: 0 = panel background, 1 = outline/ink,"
    )
    .unwrap();
    writeln!(
        f,
        "/// 2..=7 = EGA accents. See `icon_rle::LOTUS_PALETTE_RGB` for the"
    )
    .unwrap();
    writeln!(
        f,
        "/// canonical RGB values the renderer paints each index with."
    )
    .unwrap();
    writeln!(
        f,
        "pub static ICON_COLOR_BITMAPS: [[u8; COLOR_BITMAP_PIXELS]; ICON_COUNT] = ["
    )
    .unwrap();
    for (i, bm) in color_bitmaps.iter().enumerate() {
        write!(f, "    [").unwrap();
        for (j, b) in bm.iter().enumerate() {
            if j > 0 && j % 24 == 0 {
                write!(f, "\n     ").unwrap();
            }
            write!(f, "{b},").unwrap();
            if j % 24 != 23 && j != bm.len() - 1 {
                write!(f, " ").unwrap();
            }
        }
        writeln!(f, "], // {i}").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(
        f,
        "/// Per-icon flag: true when the Section-4 RLE record decoded cleanly."
    )
    .unwrap();
    writeln!(
        f,
        "/// Renderers should fall back to `ICON_BITMAPS` + category tint when this"
    )
    .unwrap();
    writeln!(
        f,
        "/// is false; the colour bitmap for such icons is all-zero."
    )
    .unwrap();
    writeln!(f, "pub const ICON_COLOR_AVAILABLE: [bool; ICON_COUNT] = [").unwrap();
    for chunk in color_available.chunks(12) {
        write!(f, "    ").unwrap();
        for v in chunk {
            write!(f, "{v}, ").unwrap();
        }
        writeln!(f).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// One-line help description per icon ID. Mirrors the").unwrap();
    writeln!(f, "/// strings 1-2-3 shows in its hover help.").unwrap();
    writeln!(f, "pub const ICON_DESCRIPTIONS: [&str; ICON_COUNT] = [").unwrap();
    for (i, d) in descriptions.iter().enumerate() {
        // Emit as a string literal — descriptions are pure ASCII, no
        // escaping needed beyond backslash and quote.
        let escaped = d.replace('\\', "\\\\").replace('"', "\\\"");
        writeln!(f, "    \"{escaped}\", // {i}").unwrap();
    }
    writeln!(f, "];").unwrap();

    println!(
        "wrote {} mono + {} colour bitmaps + descriptions to {out_path}",
        bitmaps.len(),
        color_bitmaps.len(),
    );
}
