//! Generate `crates/l123-graph/src/icon_data.rs` from a local
//! `ICONS3.DAT` file.
//!
//! Usage:
//!   cargo run -p l123-graph --example gen_icon_data -- \
//!     <path-to-ICONS3.DAT> <output-rs>
//!
//! Run once to (re)produce the committed `icon_data.rs`. The output
//! contains 105 × 72-byte monochrome bitmaps and their descriptions
//! as `pub const` arrays — used by `icons.rs` at render time so the
//! v3.4 panels look pixel-identical to the original.

use std::env;
use std::fs;
use std::io::Write;

const ICON_COUNT: usize = 105;
const BITMAP_BYTES: usize = 72;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: {} ICONS3.DAT output-rs", args[0]);
        std::process::exit(1);
    }
    let data = fs::read(&args[1]).expect("read ICONS3.DAT");
    let out_path = &args[2];

    let ptr_strings_end = u16::from_le_bytes([data[0x04], data[0x05]]) as usize;
    let ptr_mono = u16::from_le_bytes([data[0x08], data[0x09]]) as usize;

    // Bitmaps.
    let mut bitmaps: Vec<[u8; BITMAP_BYTES]> = Vec::with_capacity(ICON_COUNT);
    for i in 0..ICON_COUNT {
        let rel = u16::from_le_bytes([
            data[ptr_mono + i * 2],
            data[ptr_mono + i * 2 + 1],
        ]) as usize;
        let off = ptr_mono + rel;
        let mut buf = [0u8; BITMAP_BYTES];
        buf.copy_from_slice(&data[off..off + BITMAP_BYTES]);
        bitmaps.push(buf);
    }

    // Descriptions: null-terminated strings starting at 0xB6 (just
    // past the offset table). We collect up to ICON_COUNT of them and
    // pad with empty strings if the catalog is shorter.
    let mut descriptions: Vec<String> = Vec::new();
    let mut i = 0xB6;
    while i < ptr_strings_end && descriptions.len() < ICON_COUNT {
        let s = i;
        while i < ptr_strings_end && data[i] != 0 {
            i += 1;
        }
        let raw = std::str::from_utf8(&data[s..i]).unwrap_or("");
        // Filter out trailing garbage (binary leakage past the
        // semantically-described entries).
        let clean = if raw.chars().all(|c| c.is_ascii() && (c == ' ' || !c.is_control())) {
            raw.to_string()
        } else {
            String::new()
        };
        descriptions.push(clean);
        i += 1;
    }
    while descriptions.len() < ICON_COUNT {
        descriptions.push(String::new());
    }

    let mut f = fs::File::create(out_path).expect("create output");
    writeln!(f, "//! Auto-generated by `cargo run -p l123-graph --example gen_icon_data`.").unwrap();
    writeln!(f, "//! Source: ICONS3.DAT from Lotus 1-2-3 R3.4 (used under license).").unwrap();
    writeln!(f, "//! Edit by re-running the generator, not by hand.").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// Number of icons in the catalog.").unwrap();
    writeln!(f, "pub const ICON_COUNT: usize = {ICON_COUNT};").unwrap();
    writeln!(f, "/// Bytes per icon bitmap (24×24 monochrome, MSB-first, 0=ink).").unwrap();
    writeln!(f, "pub const BITMAP_BYTES: usize = {BITMAP_BYTES};").unwrap();
    writeln!(f, "/// Bitmap pixel dimensions.").unwrap();
    writeln!(f, "pub const BITMAP_DIM: u32 = 24;").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// 105 monochrome 24×24 icon bitmaps, indexed by icon ID.").unwrap();
    writeln!(f, "pub const ICON_BITMAPS: [[u8; BITMAP_BYTES]; ICON_COUNT] = [").unwrap();
    for (i, bm) in bitmaps.iter().enumerate() {
        write!(f, "    [").unwrap();
        for (j, b) in bm.iter().enumerate() {
            if j > 0 && j % 12 == 0 {
                write!(f, "\n     ").unwrap();
            }
            write!(f, "0x{b:02x},").unwrap();
            if j % 12 != 11 && j != bm.len() - 1 {
                write!(f, " ").unwrap();
            }
        }
        writeln!(f, "], // {i}").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();
    writeln!(f, "/// One-line help description per icon ID. Mirrors the").unwrap();
    writeln!(f, "/// strings 1-2-3 shows in its hover help.").unwrap();
    writeln!(f, "pub const ICON_DESCRIPTIONS: [&str; ICON_COUNT] = [").unwrap();
    for (i, d) in descriptions.iter().enumerate() {
        // Emit as a string literal — descriptions are pure ASCII, no
        // escaping needed beyond backslash and quote.
        let escaped = d.replace('\\', "\\\\").replace('"', "\\\"");
        writeln!(f, "    \"{escaped}\", // {i}").unwrap();
    }
    writeln!(f, "];").unwrap();

    println!("wrote {} bitmaps + descriptions to {out_path}", bitmaps.len());
}
