//! One-shot generator: read `123.HLP`, decode every body topic, and
//! emit a committable Rust source file at
//! `crates/l123-ui/src/help_topics_decoded.rs`. The file holds all
//! ~340 unique topic (title, body) pairs as `&'static str`.
//!
//! The bodies still contain residual renderer-control noise — the
//! mid-line cursor-positioning bytes from session 7 are not yet
//! fully reversed. Acceptable here because the alternative is no
//! shipped content for ~308 topics.
//!
//! Run with:
//!   cargo run -p l123-help --example generate_topics_rs
//!
//! Writes to:
//!   crates/l123-ui/src/help_topics_decoded.rs (clobbered)

use l123_help::topics;
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let hlp_path = std::env::var("L123_HLP_FILE").unwrap_or_else(|_| {
        format!(
            "{}/Documents/dosbox-cdrive/123R34/123.HLP",
            std::env::var("HOME").unwrap_or_default()
        )
    });
    let bytes = std::fs::read(&hlp_path).unwrap_or_else(|e| panic!("read {hlp_path}: {e}"));
    let ts = topics(&bytes).expect("decode topics");

    let manifest = env!("CARGO_MANIFEST_DIR");
    let out = PathBuf::from(manifest)
        .parent()
        .unwrap()
        .join("l123-ui/src/help_topics_decoded.rs");

    let mut s = String::new();
    s.push_str(GENERATED_HEADER);
    s.push_str("pub static HELP_TOPICS_DECODED: &[(&str, &str)] = &[\n");
    for t in &ts {
        let title = escape_rust_string(&t.title);
        let body = escape_rust_string(&t.body);
        writeln!(&mut s, "    (\"{title}\", \"{body}\"),").unwrap();
    }
    s.push_str("];\n");

    std::fs::write(&out, &s).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
    eprintln!(
        "wrote {} ({} topics, {} bytes)",
        out.display(),
        ts.len(),
        s.len()
    );
}

const GENERATED_HEADER: &str = "\
//! Auto-generated by `cargo run -p l123-help --example generate_topics_rs`.
//! Do not edit by hand. Regenerate after changes to the decoder or to
//! `123.HLP`.
//!
//! Each entry is `(title, body)` from the original Lotus 1-2-3 R3.4a
//! help file, Huffman-decoded and renderer-extracted. Bodies still
//! contain residual renderer-control noise (printable ASCII bytes
//! that were originally cursor-positioning commands) — see
//! `docs/HLP_DECODE_NOTES.md` session 7 for the reversal status.

#![allow(clippy::needless_raw_string_hashes)]

";

/// Escape a string for inclusion in a regular Rust `\"...\"` literal.
fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for c in s.chars() {
        match c {
            '\\' => out.push_str(r"\\"),
            '"' => out.push_str(r#"\""#),
            '\n' => out.push_str(r"\n"),
            '\r' => out.push_str(r"\r"),
            '\t' => out.push_str(r"\t"),
            '\0' => out.push_str(r"\0"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}
